/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACommasepAList extends PAList
{
    private TId _l_;
    private TAssignment _assignment_;
    private TId _r_;
    private TComma _comma_;
    private TSemicolon _semicolon_;
    private PAList _aList_;

    public ACommasepAList()
    {
        // Constructor
    }

    public ACommasepAList(
        @SuppressWarnings("hiding") TId _l_,
        @SuppressWarnings("hiding") TAssignment _assignment_,
        @SuppressWarnings("hiding") TId _r_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") PAList _aList_)
    {
        // Constructor
        setL(_l_);

        setAssignment(_assignment_);

        setR(_r_);

        setComma(_comma_);

        setSemicolon(_semicolon_);

        setAList(_aList_);

    }

    @Override
    public Object clone()
    {
        return new ACommasepAList(
            cloneNode(this._l_),
            cloneNode(this._assignment_),
            cloneNode(this._r_),
            cloneNode(this._comma_),
            cloneNode(this._semicolon_),
            cloneNode(this._aList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommasepAList(this);
    }

    public TId getL()
    {
        return this._l_;
    }

    public void setL(TId node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TAssignment getAssignment()
    {
        return this._assignment_;
    }

    public void setAssignment(TAssignment node)
    {
        if(this._assignment_ != null)
        {
            this._assignment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignment_ = node;
    }

    public TId getR()
    {
        return this._r_;
    }

    public void setR(TId node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public PAList getAList()
    {
        return this._aList_;
    }

    public void setAList(PAList node)
    {
        if(this._aList_ != null)
        {
            this._aList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_)
            + toString(this._assignment_)
            + toString(this._r_)
            + toString(this._comma_)
            + toString(this._semicolon_)
            + toString(this._aList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._assignment_ == child)
        {
            this._assignment_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._aList_ == child)
        {
            this._aList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((TId) newChild);
            return;
        }

        if(this._assignment_ == oldChild)
        {
            setAssignment((TAssignment) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((TId) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._aList_ == oldChild)
        {
            setAList((PAList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
