/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACpcCompassPt extends PCompassPt
{
    private TC _c_;

    public ACpcCompassPt()
    {
        // Constructor
    }

    public ACpcCompassPt(
        @SuppressWarnings("hiding") TC _c_)
    {
        // Constructor
        setC(_c_);

    }

    @Override
    public Object clone()
    {
        return new ACpcCompassPt(
            cloneNode(this._c_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACpcCompassPt(this);
    }

    public TC getC()
    {
        return this._c_;
    }

    public void setC(TC node)
    {
        if(this._c_ != null)
        {
            this._c_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._c_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._c_ == child)
        {
            this._c_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._c_ == oldChild)
        {
            setC((TC) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
