/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACpnCompassPt extends PCompassPt
{
    private TN _n_;

    public ACpnCompassPt()
    {
        // Constructor
    }

    public ACpnCompassPt(
        @SuppressWarnings("hiding") TN _n_)
    {
        // Constructor
        setN(_n_);

    }

    @Override
    public Object clone()
    {
        return new ACpnCompassPt(
            cloneNode(this._n_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACpnCompassPt(this);
    }

    public TN getN()
    {
        return this._n_;
    }

    public void setN(TN node)
    {
        if(this._n_ != null)
        {
            this._n_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._n_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._n_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._n_ == child)
        {
            this._n_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._n_ == oldChild)
        {
            setN((TN) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
