/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACpnwCompassPt extends PCompassPt
{
    private TNw _nw_;

    public ACpnwCompassPt()
    {
        // Constructor
    }

    public ACpnwCompassPt(
        @SuppressWarnings("hiding") TNw _nw_)
    {
        // Constructor
        setNw(_nw_);

    }

    @Override
    public Object clone()
    {
        return new ACpnwCompassPt(
            cloneNode(this._nw_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACpnwCompassPt(this);
    }

    public TNw getNw()
    {
        return this._nw_;
    }

    public void setNw(TNw node)
    {
        if(this._nw_ != null)
        {
            this._nw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nw_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nw_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nw_ == child)
        {
            this._nw_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nw_ == oldChild)
        {
            setNw((TNw) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
