/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACportPort extends PPort
{
    private TColon _colon_;
    private PCompassPt _compassPt_;

    public ACportPort()
    {
        // Constructor
    }

    public ACportPort(
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PCompassPt _compassPt_)
    {
        // Constructor
        setColon(_colon_);

        setCompassPt(_compassPt_);

    }

    @Override
    public Object clone()
    {
        return new ACportPort(
            cloneNode(this._colon_),
            cloneNode(this._compassPt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACportPort(this);
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PCompassPt getCompassPt()
    {
        return this._compassPt_;
    }

    public void setCompassPt(PCompassPt node)
    {
        if(this._compassPt_ != null)
        {
            this._compassPt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compassPt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colon_)
            + toString(this._compassPt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._compassPt_ == child)
        {
            this._compassPt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._compassPt_ == oldChild)
        {
            setCompassPt((PCompassPt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
