/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACpswCompassPt extends PCompassPt
{
    private TSw _sw_;

    public ACpswCompassPt()
    {
        // Constructor
    }

    public ACpswCompassPt(
        @SuppressWarnings("hiding") TSw _sw_)
    {
        // Constructor
        setSw(_sw_);

    }

    @Override
    public Object clone()
    {
        return new ACpswCompassPt(
            cloneNode(this._sw_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACpswCompassPt(this);
    }

    public TSw getSw()
    {
        return this._sw_;
    }

    public void setSw(TSw node)
    {
        if(this._sw_ != null)
        {
            this._sw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sw_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sw_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sw_ == child)
        {
            this._sw_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sw_ == oldChild)
        {
            setSw((TSw) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
