/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACpseCompassPt extends PCompassPt
{
    private TSe _se_;

    public ACpseCompassPt()
    {
        // Constructor
    }

    public ACpseCompassPt(
        @SuppressWarnings("hiding") TSe _se_)
    {
        // Constructor
        setSe(_se_);

    }

    @Override
    public Object clone()
    {
        return new ACpseCompassPt(
            cloneNode(this._se_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACpseCompassPt(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
