/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACpsCompassPt extends PCompassPt
{
    private TS _s_;

    public ACpsCompassPt()
    {
        // Constructor
    }

    public ACpsCompassPt(
        @SuppressWarnings("hiding") TS _s_)
    {
        // Constructor
        setS(_s_);

    }

    @Override
    public Object clone()
    {
        return new ACpsCompassPt(
            cloneNode(this._s_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACpsCompassPt(this);
    }

    public TS getS()
    {
        return this._s_;
    }

    public void setS(TS node)
    {
        if(this._s_ != null)
        {
            this._s_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._s_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._s_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._s_ == child)
        {
            this._s_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._s_ == oldChild)
        {
            setS((TS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
