/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ADigraphGraph extends PGraph
{
    private TStrict _strict_;
    private TDigraphk _digraphk_;
    private TId _id_;
    private TLeftbrace _leftbrace_;
    private PStmtList _stmtList_;
    private TRightbrace _rightbrace_;

    public ADigraphGraph()
    {
        // Constructor
    }

    public ADigraphGraph(
        @SuppressWarnings("hiding") TStrict _strict_,
        @SuppressWarnings("hiding") TDigraphk _digraphk_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TLeftbrace _leftbrace_,
        @SuppressWarnings("hiding") PStmtList _stmtList_,
        @SuppressWarnings("hiding") TRightbrace _rightbrace_)
    {
        // Constructor
        setStrict(_strict_);

        setDigraphk(_digraphk_);

        setId(_id_);

        setLeftbrace(_leftbrace_);

        setStmtList(_stmtList_);

        setRightbrace(_rightbrace_);

    }

    @Override
    public Object clone()
    {
        return new ADigraphGraph(
            cloneNode(this._strict_),
            cloneNode(this._digraphk_),
            cloneNode(this._id_),
            cloneNode(this._leftbrace_),
            cloneNode(this._stmtList_),
            cloneNode(this._rightbrace_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADigraphGraph(this);
    }

    public TStrict getStrict()
    {
        return this._strict_;
    }

    public void setStrict(TStrict node)
    {
        if(this._strict_ != null)
        {
            this._strict_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strict_ = node;
    }

    public TDigraphk getDigraphk()
    {
        return this._digraphk_;
    }

    public void setDigraphk(TDigraphk node)
    {
        if(this._digraphk_ != null)
        {
            this._digraphk_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._digraphk_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TLeftbrace getLeftbrace()
    {
        return this._leftbrace_;
    }

    public void setLeftbrace(TLeftbrace node)
    {
        if(this._leftbrace_ != null)
        {
            this._leftbrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftbrace_ = node;
    }

    public PStmtList getStmtList()
    {
        return this._stmtList_;
    }

    public void setStmtList(PStmtList node)
    {
        if(this._stmtList_ != null)
        {
            this._stmtList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtList_ = node;
    }

    public TRightbrace getRightbrace()
    {
        return this._rightbrace_;
    }

    public void setRightbrace(TRightbrace node)
    {
        if(this._rightbrace_ != null)
        {
            this._rightbrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightbrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strict_)
            + toString(this._digraphk_)
            + toString(this._id_)
            + toString(this._leftbrace_)
            + toString(this._stmtList_)
            + toString(this._rightbrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strict_ == child)
        {
            this._strict_ = null;
            return;
        }

        if(this._digraphk_ == child)
        {
            this._digraphk_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._leftbrace_ == child)
        {
            this._leftbrace_ = null;
            return;
        }

        if(this._stmtList_ == child)
        {
            this._stmtList_ = null;
            return;
        }

        if(this._rightbrace_ == child)
        {
            this._rightbrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strict_ == oldChild)
        {
            setStrict((TStrict) newChild);
            return;
        }

        if(this._digraphk_ == oldChild)
        {
            setDigraphk((TDigraphk) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._leftbrace_ == oldChild)
        {
            setLeftbrace((TLeftbrace) newChild);
            return;
        }

        if(this._stmtList_ == oldChild)
        {
            setStmtList((PStmtList) newChild);
            return;
        }

        if(this._rightbrace_ == oldChild)
        {
            setRightbrace((TRightbrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
