/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEdgeasAttrStmt extends PAttrStmt
{
    private TEdgek _edgek_;
    private PAttrList _attrList_;

    public AEdgeasAttrStmt()
    {
        // Constructor
    }

    public AEdgeasAttrStmt(
        @SuppressWarnings("hiding") TEdgek _edgek_,
        @SuppressWarnings("hiding") PAttrList _attrList_)
    {
        // Constructor
        setEdgek(_edgek_);

        setAttrList(_attrList_);

    }

    @Override
    public Object clone()
    {
        return new AEdgeasAttrStmt(
            cloneNode(this._edgek_),
            cloneNode(this._attrList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEdgeasAttrStmt(this);
    }

    public TEdgek getEdgek()
    {
        return this._edgek_;
    }

    public void setEdgek(TEdgek node)
    {
        if(this._edgek_ != null)
        {
            this._edgek_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._edgek_ = node;
    }

    public PAttrList getAttrList()
    {
        return this._attrList_;
    }

    public void setAttrList(PAttrList node)
    {
        if(this._attrList_ != null)
        {
            this._attrList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attrList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._edgek_)
            + toString(this._attrList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._edgek_ == child)
        {
            this._edgek_ = null;
            return;
        }

        if(this._attrList_ == child)
        {
            this._attrList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._edgek_ == oldChild)
        {
            setEdgek((TEdgek) newChild);
            return;
        }

        if(this._attrList_ == oldChild)
        {
            setAttrList((PAttrList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
