/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEstmtStmt extends PStmt
{
    private PEdgeStmt _edgeStmt_;

    public AEstmtStmt()
    {
        // Constructor
    }

    public AEstmtStmt(
        @SuppressWarnings("hiding") PEdgeStmt _edgeStmt_)
    {
        // Constructor
        setEdgeStmt(_edgeStmt_);

    }

    @Override
    public Object clone()
    {
        return new AEstmtStmt(
            cloneNode(this._edgeStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEstmtStmt(this);
    }

    public PEdgeStmt getEdgeStmt()
    {
        return this._edgeStmt_;
    }

    public void setEdgeStmt(PEdgeStmt node)
    {
        if(this._edgeStmt_ != null)
        {
            this._edgeStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._edgeStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._edgeStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._edgeStmt_ == child)
        {
            this._edgeStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._edgeStmt_ == oldChild)
        {
            setEdgeStmt((PEdgeStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
