/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANodeId extends PNodeId
{
    private TId _id_;
    private PPort _port_;

    public ANodeId()
    {
        // Constructor
    }

    public ANodeId(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PPort _port_)
    {
        // Constructor
        setId(_id_);

        setPort(_port_);

    }

    @Override
    public Object clone()
    {
        return new ANodeId(
            cloneNode(this._id_),
            cloneNode(this._port_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANodeId(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PPort getPort()
    {
        return this._port_;
    }

    public void setPort(PPort node)
    {
        if(this._port_ != null)
        {
            this._port_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._port_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._port_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._port_ == child)
        {
            this._port_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._port_ == oldChild)
        {
            setPort((PPort) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
