/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANodeerEdgerhs extends PEdgerhs
{
    private TEdgeop _edgeop_;
    private PNodeId _nodeId_;
    private PEdgerhs _edgerhs_;

    public ANodeerEdgerhs()
    {
        // Constructor
    }

    public ANodeerEdgerhs(
        @SuppressWarnings("hiding") TEdgeop _edgeop_,
        @SuppressWarnings("hiding") PNodeId _nodeId_,
        @SuppressWarnings("hiding") PEdgerhs _edgerhs_)
    {
        // Constructor
        setEdgeop(_edgeop_);

        setNodeId(_nodeId_);

        setEdgerhs(_edgerhs_);

    }

    @Override
    public Object clone()
    {
        return new ANodeerEdgerhs(
            cloneNode(this._edgeop_),
            cloneNode(this._nodeId_),
            cloneNode(this._edgerhs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANodeerEdgerhs(this);
    }

    public TEdgeop getEdgeop()
    {
        return this._edgeop_;
    }

    public void setEdgeop(TEdgeop node)
    {
        if(this._edgeop_ != null)
        {
            this._edgeop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._edgeop_ = node;
    }

    public PNodeId getNodeId()
    {
        return this._nodeId_;
    }

    public void setNodeId(PNodeId node)
    {
        if(this._nodeId_ != null)
        {
            this._nodeId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nodeId_ = node;
    }

    public PEdgerhs getEdgerhs()
    {
        return this._edgerhs_;
    }

    public void setEdgerhs(PEdgerhs node)
    {
        if(this._edgerhs_ != null)
        {
            this._edgerhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._edgerhs_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._edgeop_)
            + toString(this._nodeId_)
            + toString(this._edgerhs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._edgeop_ == child)
        {
            this._edgeop_ = null;
            return;
        }

        if(this._nodeId_ == child)
        {
            this._nodeId_ = null;
            return;
        }

        if(this._edgerhs_ == child)
        {
            this._edgerhs_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._edgeop_ == oldChild)
        {
            setEdgeop((TEdgeop) newChild);
            return;
        }

        if(this._nodeId_ == oldChild)
        {
            setNodeId((PNodeId) newChild);
            return;
        }

        if(this._edgerhs_ == oldChild)
        {
            setEdgerhs((PEdgerhs) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
