/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANodeasAttrStmt extends PAttrStmt
{
    private TNodek _nodek_;
    private PAttrList _attrList_;

    public ANodeasAttrStmt()
    {
        // Constructor
    }

    public ANodeasAttrStmt(
        @SuppressWarnings("hiding") TNodek _nodek_,
        @SuppressWarnings("hiding") PAttrList _attrList_)
    {
        // Constructor
        setNodek(_nodek_);

        setAttrList(_attrList_);

    }

    @Override
    public Object clone()
    {
        return new ANodeasAttrStmt(
            cloneNode(this._nodek_),
            cloneNode(this._attrList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANodeasAttrStmt(this);
    }

    public TNodek getNodek()
    {
        return this._nodek_;
    }

    public void setNodek(TNodek node)
    {
        if(this._nodek_ != null)
        {
            this._nodek_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nodek_ = node;
    }

    public PAttrList getAttrList()
    {
        return this._attrList_;
    }

    public void setAttrList(PAttrList node)
    {
        if(this._attrList_ != null)
        {
            this._attrList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attrList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nodek_)
            + toString(this._attrList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nodek_ == child)
        {
            this._nodek_ = null;
            return;
        }

        if(this._attrList_ == child)
        {
            this._attrList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nodek_ == oldChild)
        {
            setNodek((TNodek) newChild);
            return;
        }

        if(this._attrList_ == oldChild)
        {
            setAttrList((PAttrList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
