/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANodestmtNodeStmt extends PNodeStmt
{
    private PNodeId _nodeId_;

    public ANodestmtNodeStmt()
    {
        // Constructor
    }

    public ANodestmtNodeStmt(
        @SuppressWarnings("hiding") PNodeId _nodeId_)
    {
        // Constructor
        setNodeId(_nodeId_);

    }

    @Override
    public Object clone()
    {
        return new ANodestmtNodeStmt(
            cloneNode(this._nodeId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANodestmtNodeStmt(this);
    }

    public PNodeId getNodeId()
    {
        return this._nodeId_;
    }

    public void setNodeId(PNodeId node)
    {
        if(this._nodeId_ != null)
        {
            this._nodeId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nodeId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nodeId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nodeId_ == child)
        {
            this._nodeId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nodeId_ == oldChild)
        {
            setNodeId((PNodeId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
