/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANstmtStmt extends PStmt
{
    private PNodeStmt _nodeStmt_;

    public ANstmtStmt()
    {
        // Constructor
    }

    public ANstmtStmt(
        @SuppressWarnings("hiding") PNodeStmt _nodeStmt_)
    {
        // Constructor
        setNodeStmt(_nodeStmt_);

    }

    @Override
    public Object clone()
    {
        return new ANstmtStmt(
            cloneNode(this._nodeStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANstmtStmt(this);
    }

    public PNodeStmt getNodeStmt()
    {
        return this._nodeStmt_;
    }

    public void setNodeStmt(PNodeStmt node)
    {
        if(this._nodeStmt_ != null)
        {
            this._nodeStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nodeStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nodeStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nodeStmt_ == child)
        {
            this._nodeStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nodeStmt_ == oldChild)
        {
            setNodeStmt((PNodeStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
