/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASstmtStmt extends PStmt
{
    private PSubgraph _subgraph_;

    public ASstmtStmt()
    {
        // Constructor
    }

    public ASstmtStmt(
        @SuppressWarnings("hiding") PSubgraph _subgraph_)
    {
        // Constructor
        setSubgraph(_subgraph_);

    }

    @Override
    public Object clone()
    {
        return new ASstmtStmt(
            cloneNode(this._subgraph_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASstmtStmt(this);
    }

    public PSubgraph getSubgraph()
    {
        return this._subgraph_;
    }

    public void setSubgraph(PSubgraph node)
    {
        if(this._subgraph_ != null)
        {
            this._subgraph_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subgraph_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subgraph_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subgraph_ == child)
        {
            this._subgraph_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subgraph_ == oldChild)
        {
            setSubgraph((PSubgraph) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
