/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASubesEdgeStmt extends PEdgeStmt
{
    private PSubgraph _subgraph_;
    private PEdgerhs _edgerhs_;
    private PAttrList _attrList_;

    public ASubesEdgeStmt()
    {
        // Constructor
    }

    public ASubesEdgeStmt(
        @SuppressWarnings("hiding") PSubgraph _subgraph_,
        @SuppressWarnings("hiding") PEdgerhs _edgerhs_,
        @SuppressWarnings("hiding") PAttrList _attrList_)
    {
        // Constructor
        setSubgraph(_subgraph_);

        setEdgerhs(_edgerhs_);

        setAttrList(_attrList_);

    }

    @Override
    public Object clone()
    {
        return new ASubesEdgeStmt(
            cloneNode(this._subgraph_),
            cloneNode(this._edgerhs_),
            cloneNode(this._attrList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubesEdgeStmt(this);
    }

    public PSubgraph getSubgraph()
    {
        return this._subgraph_;
    }

    public void setSubgraph(PSubgraph node)
    {
        if(this._subgraph_ != null)
        {
            this._subgraph_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subgraph_ = node;
    }

    public PEdgerhs getEdgerhs()
    {
        return this._edgerhs_;
    }

    public void setEdgerhs(PEdgerhs node)
    {
        if(this._edgerhs_ != null)
        {
            this._edgerhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._edgerhs_ = node;
    }

    public PAttrList getAttrList()
    {
        return this._attrList_;
    }

    public void setAttrList(PAttrList node)
    {
        if(this._attrList_ != null)
        {
            this._attrList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attrList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subgraph_)
            + toString(this._edgerhs_)
            + toString(this._attrList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subgraph_ == child)
        {
            this._subgraph_ = null;
            return;
        }

        if(this._edgerhs_ == child)
        {
            this._edgerhs_ = null;
            return;
        }

        if(this._attrList_ == child)
        {
            this._attrList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subgraph_ == oldChild)
        {
            setSubgraph((PSubgraph) newChild);
            return;
        }

        if(this._edgerhs_ == oldChild)
        {
            setEdgerhs((PEdgerhs) newChild);
            return;
        }

        if(this._attrList_ == oldChild)
        {
            setAttrList((PAttrList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
