/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TDigraphk extends Token
{
    public TDigraphk()
    {
        super.setText("digraph");
    }

    public TDigraphk(int line, int pos)
    {
        super.setText("digraph");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDigraphk(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDigraphk(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDigraphk text.");
    }
}
