/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TGraphk extends Token
{
    public TGraphk()
    {
        super.setText("graph");
    }

    public TGraphk(int line, int pos)
    {
        super.setText("graph");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGraphk(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGraphk(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGraphk text.");
    }
}
