/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TN extends Token
{
    public TN()
    {
        super.setText("n");
    }

    public TN(int line, int pos)
    {
        super.setText("n");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TN(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTN(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TN text.");
    }
}
