/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TNw extends Token
{
    public TNw()
    {
        super.setText("nw");
    }

    public TNw(int line, int pos)
    {
        super.setText("nw");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNw(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNw(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNw text.");
    }
}
