/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TS extends Token
{
    public TS()
    {
        super.setText("s");
    }

    public TS(int line, int pos)
    {
        super.setText("s");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TS(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTS(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TS text.");
    }
}
